[package]
name = "hello-marco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "hello_marco"  # Use underscore (_) instead of dash (-)
path = "src/lib.rs"
